schema_version = "1.0.0"
id = "XD_Baker" # должен совпадать с именем папки аддона
name = "XD_Baker"
version = "1.0.0"
tagline = "Maps bake Addon for Blender"
maintainer = "Roman Askarov"
type = "add-on"
tags = ["XDevs"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
copyright = ["2024 Extreme Developers"]

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
  "./py_modules/numba-0.58.1-cp311-cp311-win_amd64.whl",
  "./py_modules/scipy-1.14.0-cp311-cp311-win_amd64.whl",
]