schema_version = "1.0.0"
id = "XD_LayeredMaterialAssembler" # должен совпадать с именем папки аддона
name = "XD Layered Material Assembler"
version = "1.0.0"
tagline = "Assemble Layered Shader from Unity"
maintainer = "Roman Askarov"
type = "add-on"
tags = ["XDevs", "BAKER"]
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2026 Extreme Developers"]