schema_version = "1.0.0"
id = "XD_CythonBuilder" # должен совпадать с именем папки аддона
name = "XD XD_CythonBuilder"
version = "0.0.1"
tagline = "Info"
maintainer = "Roman Askarov"
type = "add-on"
tags = ["info, comment"]
blender_version_min = "4.5.0"
license = ["XDevs Internal License"]