schema_version = "1.0.0"
id = "XD_ModelValidator" # должен совпадать с именем папки аддона
name = "XD_Model_Validator"
version = "0.1.4"
type = "add-on"
tagline = "Testing possible problems with scene objects."
copyright = ["2024 Extreme Developers"]
maintainer = "Roman Askarov"
license = ["XDevs Internal License"]
website = "https://extreme-developers.ru/"
blender_version_min = "4.5.1"
tags = ["XDevs"]