schema_version = "1.0.0"
id = "XD_Helpers" # должен совпадать с именем папки аддона
name = "XD Helpers"
version = "0.0.0"
tagline = "XD Helpers"
maintainer = "Roman Askarov"
type = "add-on"
tags = ["xd, helper"]
blender_version_min = "4.2.0"
license = ["XDevs Internal License"]