name: Build and Release ZIP for Changed Blender Addons

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Python toml parser
      run: pip install toml

    - name: Get changed files
      id: changed_files
      run: |
        git fetch --depth=2
        echo "files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})" >> $GITHUB_OUTPUT
    
    - name: Process changed blender manifests and create zips
      id: pack
      run: |
        changed="${{ steps.changed_files.outputs.files }}"

        if [ -z "$changed" ] || ! echo "$changed" | grep -q 'blender_manifest.toml'; then
          echo "No changed blender_manifest.toml found, skipping packaging."
          echo "created=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # проверяем есть ли файл blender_manifest.toml в текущем коммите
        touched_manifests=0
        zip_paths=""
        zip_sizes=""
        zip_hashes=""

        for file in $changed; do
          if [[ "$file" == */blender_manifest.toml ]]; then
            touched_manifests=1
          fi
        done

        # если файла blender_manifest.toml в коммите нет
        if [ $touched_manifests -eq 0 ]; then 
          echo "No blender_manifest.toml files were processed."
          echo "created=false" >> $GITHUB_OUTPUT
          exit 0
        else
          for file in $changed; do
            if [[ "$file" == */blender_manifest.toml ]]; then
              dir=$(dirname "$file")

              schema_version=$(python -c "import toml; print(toml.load('$file')['schema_version'])")
              schema_version="$schema_version"
              name=$(python -c "import toml; print(toml.load('$file')['name'])")
              id=$(python -c "import toml; print(toml.load('$file')['id'])")
              version=$(python -c "import toml; print(toml.load('$file')['version'])")
              tagline=$(python -c "import toml; print(toml.load('$file')['tagline'])")
              maintainer=$(python -c "import toml; print(toml.load('$file')['maintainer'])")
              type=$(python -c "import toml; print(toml.load('$file')['type'])")
              blender_version=$(python -c "import toml; print(toml.load('$file')['blender_version_min'])")

              tags=$(python -c "import json, toml; print(json.dumps(toml.load('$file')['tags']))")
              license=$(python -c "import json, toml; print(json.dumps(toml.load('$file')['license']))")
              copyright=$(python -c "import json, toml; print(json.dumps(toml.load('$file')['copyright']))")
              python_versions=$(python -c "import json, toml; print(json.dumps(toml.load('$file')['python_versions']))")
              
              zipname="${id}_${version}-blender-${blender_version}.zip"
              
              (cd "$dir" && zip -r "../$zipname" . -x "__pycache__/*" "*.pyc" ".vscode/*") || (echo "Failed to create zip: $zipname" && exit 1)
              touched_manifests=1

              zip_path="$dir/../$zipname"
              size=$(stat -c%s "$zip_path")
              hash=$(sha256sum "$zip_path" | cut -d' ' -f1)
              _zip_paths+="$zip_path,"
              _zip_sizes+="${size},"
              _zip_hashes+="${hash},"

              archive_url="Hello wwworld!"

              echo "zipname variable is: $zipname"
              echo "Archiving directory: $dir"
            fi
          done

          zip_paths=${_zip_paths%,}
          zip_sizes=${_zip_sizes%,}
          zip_hashes=${_zip_hashes%,}
          echo "zip_paths=$zip_paths" >> $GITHUB_OUTPUT
          echo "zip_sizes=$zip_sizes" >> $GITHUB_OUTPUT
          echo "zip_hashes=$zip_hashes" >> $GITHUB_OUTPUT

          description=""

          IFS=',' read -r -a paths_array <<< "$zip_paths"
          IFS=',' read -r -a sizes_array <<< "$zip_sizes"
          IFS=',' read -r -a hashes_array <<< "$zip_hashes"

          for i in "${!paths_array[@]}"; do
            size_clean=$(echo "${sizes_array[i]}" | xargs)
            hash_clean=$(echo "${hashes_array[i]}" | xargs)
            path_clean=$(echo "${paths_array[i]}" | xargs)

            description+="Архив: $path_clean
          Размер: $size_clean байт
          SHA256: $hash_clean

          "
          done

          echo "release_description<<EOF" >> $GITHUB_OUTPUT
          echo "$description" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          if [ $touched_manifests -eq 0 ]; then
            echo "No blender_manifest.toml files were processed."
            echo "created=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "created=true" >> $GITHUB_OUTPUT
            release_name="${id}_${version}-blender-${blender_version}"
            echo "release_name=$release_name" >> $GITHUB_OUTPUT
            echo "addon_name=${id}" >> $GITHUB_OUTPUT
            
            echo "schema_version=$schema_version" >> $GITHUB_OUTPUT
            echo "id=$id" >> $GITHUB_OUTPUT
            echo "name=$name" >> $GITHUB_OUTPUT
            echo "version=$version" >> $GITHUB_OUTPUT
            echo "tagline=$tagline" >> $GITHUB_OUTPUT
            echo "maintainer=$maintainer" >> $GITHUB_OUTPUT
            echo "type=$type" >> $GITHUB_OUTPUT
            echo "blender_version=$blender_version" >> $GITHUB_OUTPUT
            echo "archive_url=$archive_url" >> $GITHUB_OUTPUT
            echo "size_clean=$size_clean" >> $GITHUB_OUTPUT
            echo "hash_clean=$hash_clean" >> $GITHUB_OUTPUT

            echo "tags='$tags'" >> $GITHUB_OUTPUT
            echo "license='$license'" >> $GITHUB_OUTPUT
            echo "copyright='$copyright'" >> $GITHUB_OUTPUT
            echo "python_versions='$python_versions'" >> $GITHUB_OUTPUT
            
            echo "XXXXXXXXXXX"
            echo $schema_version
            echo $id
            echo $name
            echo $version
            echo $tagline
            echo $maintainer
            echo $type
            echo $blender_version
            echo $archive_url
            echo $size_clean
            echo $hash_clean

            echo "tags=$tags"
            echo "license=$license"
            echo "copyright=$copyright"
            echo "python_versions=$python_versions"
          fi
        fi

    - name: Edit index.json with Python
      if: steps.pack.outputs.created == 'true'
      env:
        id: ${{ steps.pack.outputs.addon_name }}
        schema_version: ${{ steps.pack.outputs.schema_version }}
        name: ${{ steps.pack.outputs.name }}
        tagline: ${{ steps.pack.outputs.tagline }}
        version: ${{ steps.pack.outputs.version }}
        type: ${{ steps.pack.outputs.type }}
        maintainer: ${{ steps.pack.outputs.maintainer }}
        blender_version: ${{ steps.pack.outputs.blender_version }}
        archive_url: ${{ steps.pack.outputs.archive_url }}
        size_clean: ${{ steps.pack.outputs.size_clean }}
        hash_clean: ${{ steps.pack.outputs.hash_clean }}
        tags: ${{ steps.pack.outputs.tags }}
        license: ${{ steps.pack.outputs.license }}
        copyright: ${{ steps.pack.outputs.copyright }}
        python_versions: ${{ steps.pack.outputs.python_versions }}

      run: |
        python3 - <<EOF
        import json
        import os

        with open('index.json', 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        id = os.environ['id']
        schema_version = os.environ['schema_version']
        name = os.environ['name']
        tagline = os.environ['tagline']
        version = os.environ['version']
        type = os.environ['type']
        maintainer = os.environ['maintainer']
        blender_version = os.environ['blender_version']
        archive_url = os.environ['archive_url']
        size_clean = int(os.environ['size_clean'])
        hash_clean = os.environ['hash_clean']
        
        # парсим строки в python объект
        tags_obj = json.loads(os.environ['tags'])
        license_obj = json.loads(os.environ['license'])
        copyright_obj = json.loads(os.environ['copyright'])
        python_versions_obj = json.loads(os.environ['python_versions'])
        
        item = None
        for elem in data.get('data', []):
            if elem.get('id') == id:
                item = elem
                break

        new_entry = {
            'schema_version': schema_version,
            'id': id,
            'name': name,
            'tagline': tagline,
            'version': version,
            'type': type,
            'maintainer': maintainer,
            'blender_version_min': blender_version,
            'tags': tags_obj,
            'license': license_obj,
            'copyright': copyright_obj,
            'python_versions': python_versions_obj,
            'archive_url': archive_url,
            'archive_size': size_clean,
            'archive_hash': hash_clean
        }

        if item:
            item.update(new_entry)
        else:
            if 'data' not in data:
                data['data'] = []
            data['data'].append(new_entry)

        with open('index.json', 'w', encoding='utf-8') as f:
            # json.dump(data, f, ensure_ascii=False, indent=2)
            json.dump(data, f, ensure_ascii=False)
        EOF



    
    - name: Commit and push changes
      if: steps.pack.outputs.created == 'true'
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add index.json
        if ! git diff --cached --quiet; then
          git commit -m "Update index.json"
          git push
        else
          echo "No changes to commit"
        fi

    - name: Create and push tag
      if: steps.pack.outputs.created == 'true'
      id: tag
      run: |
        TAG="release-$(date +'%Y%m%d%H%M%S')"
        git config user.name "github-actions"
        git config user.email "actions@github.com"

        if ! git diff --cached --quiet; then
          git commit -m "Update index.json"
          git push
        else
          echo "No changes to commit"
        fi

        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      if: steps.pack.outputs.created == 'true'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        #tag_name: ${{ steps.pack.outputs.addon_name }}_latest
        release_name: ${{ steps.pack.outputs.addon_name }}_latest

        body: |
          Версия релиза: ${{ steps.pack.outputs.release_name }}

          Вставьте этот путь в качестве репозитория в разделе Git Extensions параметров blender:
            https://raw.githubusercontent.com/elevenlevel/BlAddons/refs/heads/main/Extensions/index.json
          
          Таким образом у вас всегда будут самые свежие версии аддонов.

          ${{ steps.pack.outputs.release_description }}
        
        draft: false
        prerelease: false

    - name: Upload each release zip file to GitHub Release
      if: steps.pack.outputs.created == 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        shopt -s nullglob

        IFS=',' read -r -a dirs_array <<< "${{ steps.pack.outputs.zip_paths }}"

        for path in "${dirs_array[@]}"; do
          echo "$path"
          addon_name_latest=${{ steps.pack.outputs.addon_name }}
          echo "Uploading $zipfile"
          gh release upload ${{ steps.tag.outputs.tag }} "$path" --clobber
          done 